name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Hello-GitHub-Actions:
    runs-on: ubuntu-20.04
    steps:
      - run: echo This is the Ubuntu 20.04
      - run: pwd
      - run: ls -l
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo After checking out codes, we will check it ...
      - run: ls -l
      - run: chmod +x ./hello-world/hello-script.sh
      - run: ./hello-world/hello-script.sh
      - run: echo --------------------------------------------------
      - run: echo "Current GitHub workspace = ${{ job.workspace }}."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "Finish the first job :) ... "

  Explore-Some-Features-GHAs:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."